name: "Upload to Cachix"
on:
  push:
    paths:
      - '**.nix'
      - 'flake.lock'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: mrkirby153
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run .#build-all
